### ISSUE TITLE
yvm cant reach server

### ISSUE THREAD

**Issue by 1ak31sha** [cideM/fish-yvm#2] opened 2020-12-01 21:02 UTC
is this repo still active?
i got this error when trying to use yvm
```
❯ yvm use latest
Fetching releases from https://d236jo9e8rrdox.cloudfront.net/yarn-releases
(23) Failed writing body
yvm: couldn't fetch releases -- is "https://d236jo9e8rrdox.cloudfront.net/yarn-releases" a valid host?

^C⏎ 
````

**Comment by cideM** [comment] 2020-12-02 08:41
Huh, I'll check

**Comment by cideM** [comment] 2020-12-02 08:42
```
fish-yvm (master|✔) $ yvm use latest
Fetching releases from https://d236jo9e8rrdox.cloudfront.net/yarn-releases
fetching https://github.com/yarnpkg/yarn/releases/download/v1.22.10/yarn-v1.22.10.tar.gz...
```

Works for me. Can you reach that host with tracing tools? In other words: are you sure this isn't a DNS/networking issue on your end?

**Comment by 1ak31sha** [comment] 2020-12-02 18:44
```
❯ trace https://d236jo9e8rrdox.cloudfront.net/yarn-releases
Failed to open code description file https://d236jo9e8rrdox.cloudfront.net/yarn-releases
```

i navigated to the url directly and can see the json in the browser

```
[{"name":"v1.22.10","zipball_url":"https://api.github.com/repos/yarnpkg/yarn/zipball/v1.22.10","tarball_url":"https://api.github.com/repos/yarnpkg/yarn/tarball/v1.22.10","commit":{"sha":"785cda8020aa5f513d6f60b8349bca8dab9dd79b","url":"https://api.github.com/repos/yarnpkg/yarn/commits/785cda8020aa5f513d6f60b8349bca8dab9dd79b"},"node_id":"MDM6UmVmNDk5NzA2NDI6cmVmcy90YWdzL3YxLjIyLjEw"},{"name":"v1.22.5","zipball_url":"https://api.github.com/repos/yarnpkg/yarn/zipball/v1.22.5","tarball_url":"https://api.github.com/repos/yarnpkg/yarn/tarball/v1.22.5","commit":{"sha":"a3b963cf0956f0c92d024fbab9df5d1bb4a38a93","url":"https://api.github.com/repos/yarnpkg/yarn/commits/a3b963cf0956f0c92d024fbab9df5d1bb4a38a93"},"node_id":"MDM6UmVmNDk5NzA2NDI6cmVmcy90YWdzL3YxLjIyLjU="},{"name":"v1.22.4","zipball_url":"https://api.github.com/repos/yarnpkg/yarn/zipball/v1.22.4","tarball_url":"https://api.github.com/repos/yarnpkg/yarn/tarball/v1.22.4","commit":{"sha":"e5327c5f6db9d73760443caf8702af2a5548c24c","url":"https://api.github.com/repos/yarnpkg/yarn/commits/e5327c5f6db9d73760443caf8702af2a5548c24c"},"node_id":"MDM6UmVmNDk5NzA2NDI6cmVmcy90YWdzL3YxLjIyLjQ="},{"name":"v1.22.3","zipball_url":"https://api.github.com/repos/yarnpkg/yarn/zipball/v1.22.3","tarball_url":"https://api.github.com/repos/yarnpkg/yarn/tarball/v1.22.3","commit":{"sha":"92a539cca9437b03109042b049f3bc626ec1db8d","url":"https://api.github.com/repos/yarnpkg/yarn/commits/92a539cca9437b03109042b049f3bc626ec1db8d"},"node_id":"MDM6UmVmNDk5NzA2NDI6cmVmcy90YWdzL3YxLjIyLjM="},{"name":"v1.22.2","zipball_url":"https://api.github.com/repos/yarnpkg/yarn/zipball/v1.22.2","tarball_url":"https://api.github.com/repos/yarnpkg/yarn/tarball/v1.22.2","commit":{"sha":"460e0ee3da25054b2e490693af8d435bb776c871","url":"https://api.github.com/repos/yarnpkg/yarn/commits/460e0ee3da25054b2e490693af8d435bb776c871"},"node_id":"MDM6UmVmNDk5NzA2NDI6cmVmcy90YWdzL3YxLjIyLjI="},{"name":"v1.22.1","zipball_url":"https://api.github.com/repos/yarnpkg/yarn/zipball/v1.22.1","tarball_url":"https://api.github.com/repos/yarnpkg/yarn/tarball/v1.22.1","commit":{"sha":"4d6f90931d2062540d7dbb963a47ab62b5b0deba","url":"https://api.github.com/repos/yarnpkg/yarn/commits/4d6f90931d2062540d7dbb963a47ab62b5b0deba"},"node_id":"MDM6UmVmNDk5NzA2NDI6cmVmcy90YWdzL3YxLjIyLjE="},{"name":"v1.22.0","zipball_url":"https://api.github.com/repos/yarnpkg/yarn/zipball/v1.22.0","tarball_url":"https://api.github.com/repos/yarnpkg/yarn/tarball/v1.22.0","commit":{"sha":"eee67d02ed09172d5360df0fa0b9c73e23449818","url":"https://api.github.com/repos/yarnpkg/yarn/commits/eee67d02ed09172d5360df0fa0b9c73e23449818"},"node_id":"MDM6UmVmNDk5NzA2NDI6cmVmcy90YWdzL3YxLjIyLjA="},{"name":"v1.21.1","zipball_url":"https://api.github.com/repos/yarnpkg/yarn/zipball/v1.21.1","tarball_url":"https://api.github.com/repos/yarnpkg/yarn/tarball/v1.21.1","commit":{"sha":"95186d5f61ea34de7be6c59b7cfb934cc3b31988","url":"https://api.github.com/repos/yarnpkg/yarn/commits/95186d5f61ea34de7be6c59b7cfb934cc3b31988"},"node_id":"MDM6UmVmNDk5NzA2NDI6cmVmcy90YWdzL3YxLjIxLjE="},{"name":"v1.21.0","zipball_url":"https://api.github.com/repos/yarnpkg/yarn/zipball/v1.21.0","tarball_url":"https://api.github.com/repos/yarnpkg/yarn/tarball/v1.21.0","commit":{"sha":"604b4c89515830271910c0981cb5a7c008d35b70","url":"https://api.github.com/repos/yarnpkg/ya

etc
```


im not on any vpn when i tried this

**Comment by cideM** [comment] 2020-12-07 16:57
This is the `curl` command that the script runs: `curl -s 'https://d236jo9e8rrdox.cloudfront.net/yarn-releases'` does that work for you?

Try running it without the `-s` (silent) flag and see if it gives more debugging output in case it errors. Can also append `-vv` for more verbosity

**Comment by 1ak31sha** [comment] 2020-12-07 17:20
yup it runs

**Comment by cideM** [comment] 2020-12-07 19:47
Hm so I must have overlooked the `(23) Failed writing body`. It seems that this can be caused by various issues. Could you check if `$yvm_fish_data` is a valid directory that exists? Should be set as a global by `fish-yvm`. The default should be `$XDG_DATA_HOME/yvm_fish`.

**Comment by cideM** [comment] 2020-12-07 19:49
The issue here isn't `curl` rather it's the combination of `curl` plus pipe. The full command is actually

```       
 curl -s $yvm_fish_yarn_releases_url \
            | tr ',' '\n'          \
            | awk -F'":"' '
                {
                  version;
                  gsub(/"/, "", $2)
                  if ($1 ~ /name/ ) { version = $2 }
                  if ($1 ~ /tarball/) { gsub(/v/, "", version); print version, $2 }
                }
            ' >$releases 2>/dev/null
```

with `$releases` being `"$yvm_fish_data/yarn_releases"`

Which operating system are you on?

**Comment by 1ak31sha** [comment] 2020-12-07 20:22
❯ $yvm_fish_data
fish: The expanded command was empty.

i am on macOS catalina 10.15 .7

**Comment by cideM** [comment] 2020-12-08 09:39
**Also do `ls $yvm_fish_data` sorry**

Interesting, so I guess you don't have anything in `$XDG_DATA_HOME/yvm_fish`? Try `~/.local/share/yvm_fish`. It looks like the directories for `fish-yvm` were never created or that it can't create them. The first thing the script does is check if that path is a directory and if that's not the case it'll create the directory.

**Comment by 1ak31sha** [comment] 2020-12-08 17:40
❯ ls $yvm_fish_data
total 120
-rw-r--r--  1 lakeishapogrzeba  staff   206B 30 Oct 15:33 change_background.applescript


-> OK. what happened here is it just `ls`'ed my current directory, becuase $yvm_fish_data returned nothing

**Comment by 1ak31sha** [comment] 2020-12-08 17:41
❯ cd ~/.local/share/yvm_fish

.local/share/yvm_fish
❯ ls
total 0
-rw-r--r--  1 lakeishapogrzeba  staff     0B  2 Dec 13:43 yarn_releases

**Comment by cideM** [comment] 2020-12-16 21:10
Sorry for the delay :( 

Whenever you run any `yvm` command it executes

```
    if not test -d $yvm_fish_data
        mkdir -p $yvm_fish_data
    end
```

which is set by

```
set -q XDG_DATA_HOME
or set XDG_DATA_HOME ~/.local/share

set -g yvm_fish_data $XDG_DATA_HOME/yvm_fish
```

so I'm really, really surprised that this didn't work for you.

Can you manually create `~/.local/share/yvm_fish` and then explicitly set `set -g yvm_fish_data ~/.local/share/yvm_fish` and re-run `yvm use latest`? 

Also for good measure maybe search your home folder for `yvm_fish` in case it landed somewhere else.

Really strange... there are no other errors?

**Comment by cideM** [comment] 2021-03-08 10:30
Feel free to reopen if this is still an issue

**Comment by rveldhuizen** [comment] 2021-03-17 13:44
Hi there,

I found the same issue. Checked already everything above and the pats/folders where indeed already created.

By running the command getting the follwoing message:

```
yvm use latest
Fetching releases from https://d236jo9e8rrdox.cloudfront.net/yarn-releases
yvm: couldn't fetch releases -- is "https://d236jo9e8rrdox.cloudfront.net/yarn-releases" a valid host?
```
With the curl commands (with or without -s) getting a correct response!

**Comment by cideM** [comment] 2021-03-18 10:46
Interestingly you don't get the `(23) Failed writing body` error. What OS are you using and what's your curl version?

**Comment by rveldhuizen** [comment] 2021-03-18 10:51
curl 7.64.1 on a Mac OS Big Sur (11.2.3). I've also tried to use the command directly yesterday. I noticed that there was a error next on the part (what could be i'm missing the variable)
`fish: Invalid redirection target:
            ' >$releases 2>/dev/null
              ^`

**Comment by cideM** [comment] 2021-03-18 11:11
I pushed a branch called `improve-curl-errors`. On this branch you should get the raw output from curl when releases are updated for whatever reasons. Using `-s` was just not a good idea. It would be super cool if you could give this a try and let me know what you see.

@1ak31sha  might also be interesting to you  :pray:

**Comment by rveldhuizen** [comment] 2021-03-18 12:36
The first hit results in
`Version  not found. Consider running "yvm ls" and check that the version is correct.`
I've tweaked your script a bit with a -S (show errors) and that results in the following
`yvm use latest
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 61930  100 61930    0     0   499k      0 --:--:-- --:--:-- --:--:--  499k
awk: illegal statement
 input record number 1, file
 source line number 3
Version  not found. Consider running "yvm ls" and check that the version is correct.`

**Comment by cideM** [comment] 2021-03-18 18:23
Which `awk` version are you using?

This is the content of the temp file that's ultimately sent through `tr` and `awk`

```json
[{"name":"v1.22.10","zipball_url":"https://api.github.com/repos/yarnpkg/yarn/zipball/v1.22.10","tarball_url":"https://api.github.com/repos/yarnpkg/yarn/tarball/v1.22.10","commit":{"sha":"785cda8020aa5f513d6f60b8349bca8dab9dd79b","url":"https://api.github.com/repos/yarnpkg/yarn/commits/785cda8020aa5f513d6f60b8349bca8dab9dd79b"},"node_id":"MDM6UmVmNDk5NzA2NDI6cmVmcy90YWdzL3YxLjIyLjEw"}]
```

```shell
$ echo '[{"name":"v1.22.10","zipball_url":"https://api.github.com/repos/yarnpkg/yarn/zipball/v1.22.10","tarball_url":"https://api.github.com/repos/yarnpkg/yarn/tarball/v1.22.10","commit":{"sha":"785cda8020aa5f513d6f60b8349bca8dab9dd79b","url":"https://api.github.com/repos/yarnpkg/yarn/commits/785cda8020aa5f513d6f60b8349bca8dab9dd79b"},"node_id":"MDM6UmVmNDk5NzA2NDI6cmVmcy90YWdzL3YxLjIyLjEw"}]' | tr ',' '\n'
[{"name":"v1.22.10"
"zipball_url":"https://api.github.com/repos/yarnpkg/yarn/zipball/v1.22.10"
"tarball_url":"https://api.github.com/repos/yarnpkg/yarn/tarball/v1.22.10"
"commit":{"sha":"785cda8020aa5f513d6f60b8349bca8dab9dd79b"
"url":"https://api.github.com/repos/yarnpkg/yarn/commits/785cda8020aa5f513d6f60b8349bca8dab9dd79b"}
"node_id":"MDM6UmVmNDk5NzA2NDI6cmVmcy90YWdzL3YxLjIyLjEw"}]
$ echo '[{"name":"v1.22.10","zipball_url":"https://api.github.com/repos/yarnpkg/yarn/zipball/v1.22.10","tarball_url":"https://api.github.com/repos/yarnpkg/yarn/tarball/v1.22.10","commit":{"sha":"785cda8020aa5f513d6f60b8349bca8dab9dd79b","url":"https://api.github.com/repos/yarnpkg/yarn/commits/785cda8020aa5f513d6f60b8349bca8dab9dd79b"},"node_id":"MDM6UmVmNDk5NzA2NDI6cmVmcy90YWdzL3YxLjIyLjEw"}]' | tr ',' '\n' | awk -F'":"' '{ version;
    gsub(/"/, "", $2)
    if ($1 ~ /name/ ) { version = $2 }
    if ($1 ~ /tarball/) { gsub(/v/, "", version); print version, $2 } }'
1.22.10 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.22.10

```

**Comment by cideM** [comment] 2021-03-18 18:25
This is the file that's generated 

```
1.22.10 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.22.10
1.22.5 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.22.5
1.22.4 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.22.4
1.22.3 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.22.3
1.22.2 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.22.2
1.22.1 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.22.1
1.22.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.22.0
1.21.1 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.21.1
1.21.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.21.0
1.20.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.20.0
1.19.2 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.19.2
1.19.1 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.19.1
1.19.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.19.0
1.18.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.18.0
1.17.3 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.17.3
1.17.2 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.17.2
1.17.1 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.17.1
1.17.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.17.0
1.16.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.16.0
1.15.2 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.15.2
1.15.1 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.15.1
1.15.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.15.0
1.14.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.14.0
1.13.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.13.0
1.12.3 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.12.3
1.12.2 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.12.2
1.12.1 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.12.1
1.12.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.12.0
1.11.1 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.11.1
1.11.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.11.0
1.10.1 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.10.1
1.10.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.10.0
1.9.4 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.9.4
1.9.3 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.9.3
1.9.2 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.9.2
1.9.1 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.9.1
1.9.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.9.0
1.8.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.8.0
1.7.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.7.0
1.6.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.6.0
1.5.1 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.5.1
1.5.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.5.0
1.4.1 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.4.1
1.4.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.4.0
1.3.2 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.3.2
1.3.1 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.3.1
1.3.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.3.0
1.2.1 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.2.1
1.2.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.2.0
1.1.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.1.0
1.1.0-exp.2 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.1.0-exp.2
1.0.2 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.0.2
1.0.1 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.0.1
1.0.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v1.0.0
0.28.4 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.28.4
0.28.3 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.28.3
0.28.2 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.28.2
0.28.1 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.28.1
0.28.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.28.0
0.27.5 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.27.5
0.27.4 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.27.4
0.27.3 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.27.3
0.27.2 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.27.2
0.27.1 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.27.1
0.27.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.27.0
0.26.1 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.26.1
0.26.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.26.0
0.25.4 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.25.4
0.25.3 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.25.3
0.25.2 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.25.2
0.25.1 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.25.1
0.25.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.25.0
0.24.6 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.24.6
0.24.5 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.24.5
0.24.4 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.24.4
0.24.3 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.24.3
0.24.2 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.24.2
0.24.1 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.24.1
0.24.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.24.0
0.23.4 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.23.4
0.23.3 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.23.3
0.23.2 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.23.2
0.23.1 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.23.1
0.23.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.23.0
0.22.1 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.22.1
0.22.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.22.0
0.21.3 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.21.3
0.21.2 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.21.2
0.21.1 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.21.1
0.21.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.21.0
0.21.0-pre https://api.github.com/repos/yarnpkg/yarn/tarball/v0.21.0-pre
0.20.4 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.20.4
0.20.3 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.20.3
0.20.2 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.20.2
0.20.1 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.20.1
0.20.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.20.0
0.20.0-0 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.20.0-0
0.19.1 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.19.1
0.19.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.19.0
0.19.0-2-exp https://api.github.com/repos/yarnpkg/yarn/tarball/v0.19.0-2-exp
0.19.0-0 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.19.0-0
0.18.2 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.18.2
0.18.1 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.18.1
0.18.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.18.0
0.18.0-0 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.18.0-0
0.17.10 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.17.10
0.17.9 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.17.9
0.17.8 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.17.8
0.17.7 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.17.7
0.17.6 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.17.6
0.17.5 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.17.5
0.17.4 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.17.4
0.17.3 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.17.3
0.17.2 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.17.2
0.17.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.17.0
0.17.0-0 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.17.0-0
0.16.1 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.16.1
0.16.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.16.0
0.15.1 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.15.1
0.15.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.15.0
0.14.3 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.14.3
0.14.2 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.14.2
0.14.1 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.14.1
0.14.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.14.0
0.13.6 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.13.6
0.13.5 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.13.5
0.13.4 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.13.4
0.13.3 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.13.3
0.13.2 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.13.2
0.13.1 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.13.1
0.13.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.13.0
0.12.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.12.0
0.11.2 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.11.2
0.11.1 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.11.1
0.11.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.11.0
0.10.1 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.10.1
0.10.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.10.0
0.9.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.9.0
0.8.3 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.8.3
0.8.2 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.8.2
0.8.1 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.8.1
0.8.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.8.0
0.7.1 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.7.1
0.7.0 https://api.github.com/repos/yarnpkg/yarn/tarball/v0.7.0
pre-release https://api.github.com/repos/yarnpkg/yarn/tarball/pre-release
1.22.10 https://api.github.com/repos/yarnpkg/yarn/tarball/1.22.10
0.7.0 https://api.github.com/repos/yarnpkg/yarn/tarball/0.7.0
0.6.1 https://api.github.com/repos/yarnpkg/yarn/tarball/0.6.1
0.6.0 https://api.github.com/repos/yarnpkg/yarn/tarball/0.6.0
0.5.0 https://api.github.com/repos/yarnpkg/yarn/tarball/0.5.0
0.4.9 https://api.github.com/repos/yarnpkg/yarn/tarball/0.4.9
0.4.8 https://api.github.com/repos/yarnpkg/yarn/tarball/0.4.8
0.4.7 https://api.github.com/repos/yarnpkg/yarn/tarball/0.4.7
0.4.6 https://api.github.com/repos/yarnpkg/yarn/tarball/0.4.6
0.4.5 https://api.github.com/repos/yarnpkg/yarn/tarball/0.4.5
0.4.4 https://api.github.com/repos/yarnpkg/yarn/tarball/0.4.4
0.4.3 https://api.github.com/repos/yarnpkg/yarn/tarball/0.4.3
0.4.2 https://api.github.com/repos/yarnpkg/yarn/tarball/0.4.2
0.4.1 https://api.github.com/repos/yarnpkg/yarn/tarball/0.4.1
0.4.0 https://api.github.com/repos/yarnpkg/yarn/tarball/0.4.0
0.3.0 https://api.github.com/repos/yarnpkg/yarn/tarball/0.3.0
0.2.0 https://api.github.com/repos/yarnpkg/yarn/tarball/0.2.0
```

and it's run through `awk` now I'm assuming that this is where things are falling apart

**Comment by rveldhuizen** [comment] 2021-03-18 18:51
I'm using awk version 20200816

**Comment by cideM** [comment] 2021-03-19 09:20
Is that the output of `awk --version`? 

```
$ awk --version
GNU Awk 5.1.0, API: 3.0
Copyright (C) 1989, 1991-2020 Free Software Foundation.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see http://www.gnu.org/licenses/.
```

**Comment by cideM** [comment] 2021-03-19 09:24
Also can you try to run 

```shell
$ echo '[{"name":"v1.22.10","zipball_url":"https://api.github.com/repos/yarnpkg/yarn/zipball/v1.22.10","tarball_url":"https://api.github.com/repos/yarnpkg/yarn/tarball/v1.22.10","commit":{"sha":"785cda8020aa5f513d6f60b8349bca8dab9dd79b","url":"https://api.github.com/repos/yarnpkg/yarn/commits/785cda8020aa5f513d6f60b8349bca8dab9dd79b"},"node_id":"MDM6UmVmNDk5NzA2NDI6cmVmcy90YWdzL3YxLjIyLjEw"}]' | tr ',' '\n' | awk -F'":"' '{ version;
    gsub(/"/, "", $2)
    if ($1 ~ /name/ ) { version = $2 }
    if ($1 ~ /tarball/) { gsub(/v/, "", version); print version, $2 } }'
```

^ this should fail can run with `curl https://gist.githubusercontent.com/cideM/06b309a2f9cda27972458a9df2482c68/raw/03870fcc10ff53ed84f0e3753c2a7c8f213654ae/issue.sh | sh`

```shell
$ echo '[{"name":"v1.22.10","zipball_url":"https://api.github.com/repos/yarnpkg/yarn/zipball/v1.22.10","tarball_url":"https://api.github.com/repos/yarnpkg/yarn/tarball/v1.22.10","commit":{"sha":"785cda8020aa5f513d6f60b8349bca8dab9dd79b","url":"https://api.github.com/repos/yarnpkg/yarn/commits/785cda8020aa5f513d6f60b8349bca8dab9dd79b"},"node_id":"MDM6UmVmNDk5NzA2NDI6cmVmcy90YWdzL3YxLjIyLjEw"}]' | tr ',' '\n' | awk -F'":"' '{ version; gsub(/"/, "", $2); if ($1 ~ /name/ ) { version = $2; } if ($1 ~ /tarball/) { gsub(/v/, "", version); print version, $2; } }'
```

^ hopefully this doesn't fail. run with `curl https://gist.githubusercontent.com/cideM/0e35d6b5d8c859e3017fefbed63846c1/raw/c02053641f531775a68139ff8f1071cc980f28dd/issue2.sh | sh`

I think it's a silly syntax incompatibility between AWK versions

**Comment by rveldhuizen** [comment] 2021-03-19 10:33
That was the issue... it seems that there was not a correct verision of aws. By installing it, it worked just out of the box!

`brew install gawk`

That was the missing thing! Thanks for your support.

**Comment by cideM** [comment] 2021-03-19 13:48
Hummmmmmm... now I'm wondering how old your awk version was. If this is likely to happen for many people then maybe I can just figure out which part of my query doesn't work and then make it work for those older versions too. I'll have to find an older `awk` and play around with it. Thanks for your input and patience!

**Comment by cideM** [comment] 2021-03-19 18:54
Error handling should now be better #3 I don't know how easy it is for me to get a reasonably old `awk` version to test this. I also changed the `awk` call slightly. Maybe someone who cna reproduce the error could try the various snippets or get back to me for some `awk` debugging. It's a tiny awk script after all

**Closed as completed by cideM** 2021-03-19 18:54 UTC
